export const mobilenetToInterpretation: Record<string, string> = {
  // MobileNet Label -> Interpretation ID
  'bald eagle': 'eagle',
  'kite': 'eagle',
  'vulture': 'eagle',
  'great grey owl': 'owl',
  'hen': 'bird',
  'cock': 'bird',
  'ostrich': 'bird',
  'duck': 'duck',
  'goose': 'duck',
  'swan': 'duck',
  'black swan': 'duck',
  'lion': 'lion',
  'tiger': 'cat',
  'tabby': 'cat',
  'tiger cat': 'cat',
  'persian cat': 'cat',
  'siamese cat': 'cat',
  'egyptian cat': 'cat',
  'chow': 'dog',
  'pug': 'dog',
  'chihuahua': 'dog',
  'beagle': 'dog',
  'golden retriever': 'dog',
  'malamute': 'dog',
  'kelpie': 'dog',
  'german shepherd': 'dog',
  'labrador retriever': 'dog',
  'pomeranian': 'dog',
  'hamster': 'mouse',
  'mouse': 'mouse',
  'hog': 'pig',
  'pig': 'pig',
  'wild boar': 'pig',
  'hedgehog': 'hedgehog',
  'porcupine': 'hedgehog',
  'elephant': 'elephant',
  'tusker': 'elephant',
  'indian elephant': 'elephant',
  'african elephant': 'elephant',
  'camel': 'camel',
  'arabian camel': 'camel',
  'guinea pig': 'mouse',
  'balloon': 'ball',
  'soccer ball': 'ball',
  'basketball': 'ball',
  'rugby ball': 'ball',
  'golf ball': 'ball',
  'baseball': 'ball',
  'tennis ball': 'ball',
  'volleyball': 'ball',
  'cup': 'cup',
  'coffee mug': 'cup',
  'coffeepot': 'cup',
  'teapot': 'cup',
  'pitcher': 'bottle',
  'water bottle': 'bottle',
  'wine bottle': 'bottle',
  'beer bottle': 'bottle',
  'vase': 'bottle',
  'hammer': 'hammer',
  'hatchet': 'hatchet',
  'axe': 'axe',
  'cleaver': 'hatchet',
  'knife': 'knife',
  'letter opener': 'dagger',
  'shoe': 'shoe',
  'running shoe': 'shoe',
  'clog': 'shoe',
  'loafer': 'shoe',
  'boot': 'shoe',
  'sandal': 'shoe',
  'broom': 'broom',
  'mop': 'broom',
  'torch': 'torch',
  'lighter': 'torch',
  'candle': 'torch',
  'bell': 'bell',
  'church bell': 'bell',
  'cowbell': 'bell',
  'gong': 'bell',
  'scale': 'scales_justice',
  'balance beam': 'scales_justice',
  'ruler': 'scales',
  'chain saw': 'saw',
  'scissors': 'scales',
  'ship': 'ship',
  'liner': 'ship',
  'container ship': 'ship',
  'schooner': 'ship',
  'speedboat': 'boat',
  'canoe': 'boat',
  'lifeboat': 'boat',
  'gondola': 'boat',
  'submarine': 'boat',
  'aircraft carrier': 'ship',
  'car': 'car',
  'sports car': 'car',
  'racer': 'car',
  'convertible': 'car',
  'minivan': 'car',
  'limousine': 'car',
  'jeep': 'car',
  'ambulance': 'car',
  'police van': 'car',
  'tow truck': 'car',
  'trailer truck': 'car',
  'moving van': 'car',
  'bicycle': 'wheel',
  'tricycle': 'wheel',
  'mountain bike': 'wheel',
  'unicycle': 'wheel',
  'electric guitar': 'guitar',
  'acoustic guitar': 'guitar',
  'banjo': 'guitar',
  'violin': 'guitar',
  'cello': 'guitar',
  'grand piano': 'piano',
  'upright': 'piano',
  'sax': 'trumpet',
  'trumpet': 'trumpet',
  'trombone': 'trumpet',
  'french horn': 'trumpet',
  'cornet': 'trumpet',
  'flute': 'pipe',
  'oboe': 'pipe',
  'flower pot': 'flower',
  'daisy': 'flower',
  'rose': 'flower',
  'tulip': 'flower',
  'orchid': 'flower',
  'greenhouse': 'garden',
  'corn': 'plant',
  'ear': 'plant',
  'tree': 'tree',
  'spider': 'spider',
  'tarantula': 'spider',
  'garden spider': 'spider',
  'black widow': 'spider',
  'centipede': 'worm',
  'worm': 'worm',
  'nematode': 'worm',
  'snake': 'snake',
  'green mamba': 'snake',
  'python': 'snake',
  'boa constrictor': 'snake',
  'cobbra': 'snake',
  'water snake': 'snake',
  'sea snake': 'snake',
  'lizard': 'lizard',
  'frilled lizard': 'lizard',
  'alligator lizard': 'lizard',
  'green lizard': 'lizard',
  'komodo dragon': 'dragon',
  'african chameleon': 'lizard',
  'frog': 'frog',
  'tree frog': 'frog',
  'bullfrog': 'frog',
  'tailed frog': 'frog',
  'turtle': 'turtle',
  'terrapin': 'turtle',
  'box turtle': 'turtle',
  'mud turtle': 'turtle',
  'sea turtle': 'turtle',
  'fish': 'fish',
  'goldfish': 'fish',
  'stingray': 'fish',
  'shark': 'fish',
  'hammerhead': 'fish',
  'electric ray': 'fish',
  'barracuda': 'fish',
  'coho': 'fish',
  'tench': 'fish',
  'rock beauty': 'fish',
  'anemone fish': 'fish',
  'sturgeon': 'fish',
  'gar': 'fish',
  'lionfish': 'fish',
  'puffer': 'fish',
  'starfish': 'star',
  'sea urchin': 'hedgehog',
  'jellyfish': 'fish',
  'crab': 'pincers',
  'lobster': 'pincers',
  'crayfish': 'pincers',
  'hermit crab': 'pincers',
  'isopod': 'pincers',
  'snail': 'worm',
  'slug': 'worm',
  'conch': 'shell',
  'ant': 'ant',
  'bee': 'bee',
  'wasp': 'bee',
  'fly': 'insect',
  'dragonfly': 'insect',
  'grasshopper': 'insect',
  'cricket': 'insect',
  'beetle': 'insect',
  'butterfly': 'butterfly',
  'moth': 'butterfly',
  'banana': 'fruit',
  'apple': 'apple',
  'strawberry': 'fruit',
  'orange': 'fruit',
  'lemon': 'fruit',
  'fig': 'fruit',
  'pineapple': 'fruit',
  'pomegranate': 'fruit',
  'mushroom': 'mushroom',
  'broccoli': 'vegetable',
  'cauliflower': 'vegetable',
  'zucchini': 'vegetable',
  'cucumber': 'vegetable',
  'artichoke': 'vegetable',
  'bell pepper': 'vegetable',
  'cardoon': 'vegetable',
  'head cabbage': 'vegetable',
  'rapeseed': 'plant',
  'yellow ladys slipper': 'flower',
  'acorn': 'nut',
  'hip': 'fruit',
  'buckeye': 'nut',
  'coral fungus': 'mushroom',
  'agaric': 'mushroom',
  'gyromitra': 'mushroom',
  'stinkhorn': 'mushroom',
  'earthstar': 'mushroom',
  'hen-of-the-woods': 'mushroom',
  'bolete': 'mushroom',
  'toilet seat': 'shoe', // Common misclassification for roundish things, maybe safer to ignore or map to general luck?
  // Add more mappings as needed based on testing
};
